In [1]:
import torch

In [2]:
torch.version.__version__

'1.13.0+cu117'

In [3]:
a=torch.ones(3,3)

In [4]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
b=torch.ones(3,3)

In [6]:
a+b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [7]:
torch.cuda.is_available()

True

In [10]:
a= a.to('cuda')#把a 向量放到cuda中
b =b.to('cuda')
a+b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [11]:
b=b.to('cpu')

In [12]:
a + b#这时候不能运算，因为a 在gpu,b 在cpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!