In [1]:
a = [1.0,2.0,3.0]

In [2]:
a[0]

1.0

In [3]:
import torch

In [4]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[2]

tensor(1.)

In [6]:
float(a[2])

1.0

In [7]:
a[2] = 2.0

In [8]:
a

tensor([1., 1., 2.])

In [9]:
points = torch.zeros(6)
points[0] = 4.0
points[1] =1.0
points[2] =5.0
points[3] =3.0
points[4] =2.0
points[5] =1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
points = torch.tensor([4,5,2,1,5,4])
points

tensor([4, 5, 2, 1, 5, 4])

In [11]:
points[0]

tensor(4)

In [12]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points[0,0]

tensor(4.)

In [15]:
#storage

In [16]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0],[2.0,2.0],[1.0,4.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.],
        [2., 2.],
        [1., 4.]])

In [17]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
 2.0
 2.0
 1.0
 4.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 10]

In [18]:
second_point = points[3]
second_point,second_point.storage_offset()#storage_offset()表示某个张量数据在存储中相对起始数据的偏移量

(tensor([2., 2.]), 6)

In [19]:
second_point.size(),second_point.shape

(torch.Size([2]), torch.Size([2]))

In [20]:
points.size(),points.shape

(torch.Size([5, 2]), torch.Size([5, 2]))

In [21]:
second_point[0]

tensor(2.)

In [22]:
second_point

tensor([2., 2.])

In [23]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.],
        [2., 2.],
        [1., 4.]])

In [24]:
second_point[0]=1.0

In [25]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.],
        [1., 2.],
        [1., 4.]])

In [26]:
second_point = points[1].clone()

In [27]:
second_point

tensor([5., 3.])

In [28]:
second_point[1] = 0.

In [29]:
second_point

tensor([5., 0.])

In [30]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.],
        [1., 2.],
        [1., 4.]])

In [31]:
second_point.storage_offset()

0

In [32]:
second_point.stride()#.stride() 从一个张量里的一个元素，跳到相邻元素，在内存中的间隔距离，（1，），逗号左边表示到列方向距离，右边代表行间距

(1,)

In [33]:
points.stride()

(2, 1)

In [34]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.],
        [1., 2.],
        [1., 4.]])

In [35]:
points_t = points.t()#矩阵的转置
points_t

tensor([[4., 5., 2., 1., 1.],
        [1., 3., 1., 2., 4.]])

In [37]:
id(points.storage())==id(points_t.storage())

True

In [38]:
points_t.stride()

(1, 2)

In [40]:
points.stride()

(2, 1)

In [41]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
 1.0
 2.0
 1.0
 4.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 10]

In [42]:
points.storage()#转置前后不改变数据的存储位置

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
 1.0
 2.0
 1.0
 4.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 10]

In [44]:
some_t = torch.ones(3,4,5)#(通道，行，列)
some_t.stride()

(20, 5, 1)

In [47]:
transpose_t = some_t.transpose(0,2)#transpose(),更换维度，这里将第零维和第二维更换，变成(5,4,3)
transpose_t.shape

torch.Size([5, 4, 3])

In [48]:
transpose_t.stride()

(1, 5, 20)

In [49]:
points.is_contiguous()#查看张量顺序是否和内存顺序一样，是连续的

True