In [1]:
import torch

In [2]:
double_points = torch.ones(10,2,dtype=torch.double) #数据类型的定义方式1 dtype=
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)

In [4]:
double_points.dtype,short_points.dtype

(torch.float64, torch.int16)

In [5]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

### 数据类型的定义方式2 torch.short() torch.double() ... 书本p50

In [8]:
double_points = torch.zeros(10,2).double()
short_points = torch.zeros(10,2).short()

In [9]:
short_points

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

### 定义数据类型的第三种方式 torch.to(dtype) ,to 还可以用于将数据转到cpu 或者gpu

In [10]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(torch.short)

In [14]:
points_64 = torch.rand(5,dtype=torch.double)
points_64

tensor([0.8164, 0.9972, 0.7721, 0.8337, 0.2302], dtype=torch.float64)

In [15]:
points_short = points_64.to(torch.short)
print(points_64)
print(points_short)

tensor([0.8164, 0.9972, 0.7721, 0.8337, 0.2302], dtype=torch.float64)
tensor([0, 0, 0, 0, 0], dtype=torch.int16)


In [16]:
a = torch.tensor(12.3)
a.to(torch.short) #浮点型转整形，向下取整，而不是四舍五入

tensor(12, dtype=torch.int16)

In [17]:
points_64*points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)