In [1]:
import torch

In [2]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [3]:
some_list[1:]

[1, 2, 3, 4, 5]

In [4]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [5]:
some_list[:5]

[0, 1, 2, 3, 4]

In [6]:
some_list[-1]

5

In [7]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [8]:
some_list[1:4:2]# [起：始：间隔]

[1, 3]

In [9]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points[1:,0]

tensor([5., 2.])

In [11]:
a=points[None]
a.shape,points.shape

(torch.Size([1, 3, 2]), torch.Size([3, 2]))

In [12]:
points= torch.ones(3,4)
points_np = points.numpy()

In [13]:
points,points_np

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [14]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### torch 存储方式

In [15]:
torch.save(points,'../data/p1ch3/slf3_ourpoints.t')#方式1

In [16]:
with open('../data/p1ch3/slf3_ourpoints.t','wb') as f: #方式2
    torch.save(points,f)

In [17]:
###数据加载
a = torch.load("../data/p1ch3/slf3_ourpoints.t")
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
import h5py #这是一个常用来读写大型网络的包

In [20]:
f = h5py.File('../data/p1ch3/slf3_ourpoints.hdf5','w')
dset = f.create_dataset('coords',data=points.numpy()) #将当前的points参数，转成numpy格式，存到.hdf5文件中，且给当前数据命名为 'coords'
f.close()

In [21]:
f = h5py.File('../data/p1ch3/slf3_ourpoints.hdf5','r')

In [22]:
dset= f['coords']
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [24]:
last_points = dset[:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [25]:
points = torch.tensor(dset[-2:])
f.close()

In [26]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [27]:
points_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]],device='cuda')

In [28]:
points + points_gpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [29]:
points.to('cuda') #此时还是不能加，因为points还cpu
points +points_gpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [30]:
points = points.to('cuda')
points+points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')

In [31]:
points = points.to(device='cuda:0')#当有多个gpu时用

In [32]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points = 2*points
points_gpu=2*points.to(device='cuda')
points_gpu

tensor([[16.,  4.],
        [20., 12.],
        [ 8.,  4.]], device='cuda:0')

In [33]:
points_cpu = points_gpu.to(device='cpu')