In [1]:
import torch

In [2]:
a = torch.tensor(list(range(9)))

In [3]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a.size(),a.storage_offset(),a.stride()

(torch.Size([9]), 0, (1,))

In [5]:
b=a.view(3,3)

In [6]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [11]:
id(b.storage()),id(a.storage())

(140156927808464, 140156927808464)

In [15]:
b[1,1]=4

In [16]:
a,b

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [17]:
c= b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [19]:
c.size()

torch.Size([2, 2])

In [20]:
c.storage_offset()

4

In [21]:
c.stride()

(3, 1)

In [22]:
a=torch.tensor(list(range(9)))
a.dtype

torch.int64

In [23]:
a.to(float)#注意a.to(dtype)只是创建了新的数值类型，需要重新
a.dtype

torch.int64

In [24]:
a = a.to(float)
a.dtype

torch.float64

In [25]:
a

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [27]:
torch.cos(a),a

(tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
         -0.1455], dtype=torch.float64),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [28]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)

In [29]:
a.to(int),a

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))