In [1]:
import torch
_ =torch.tensor([0.2126,0.7152,0.0722],names=['c'])

/tmp/ipykernel_62996/3334078019.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1405.)
  _ =torch.tensor([0.2126,0.7152,0.0722],names=['c'])


In [2]:
img_t =torch.randn(3,5,5)
weight = torch.tensor([0.2126,0.7152,0.0722])

In [3]:
batch_t = torch.randn(2,3,5,5) #shape [batch,channels,rows,columns]

In [4]:
img_gray_naive = img_t.mean(-3)#在倒数第三个维度取平均
img_gray_naive.shape

torch.Size([5, 5])

In [5]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive.shape

torch.Size([2, 5, 5])

In [6]:
weight = torch.tensor([0.2126,0.7152,0.0722])
unsqueenzed_weight = torch.unsqueeze(weight,-1)
unsqueenzed_weight,unsqueenzed_weight.shape

(tensor([[0.2126],
         [0.7152],
         [0.0722]]),
 torch.Size([3, 1]))

In [7]:
unsqueenzed_weight=unsqueenzed_weight.unsqueeze(-1)
unsqueenzed_weight,unsqueenzed_weight.shape

(tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0722]]]),
 torch.Size([3, 1, 1]))

In [8]:
img_weights = (img_t*unsqueenzed_weight)
img_weights.shape

torch.Size([3, 5, 5])

In [9]:
batch_weight = (batch_t*unsqueenzed_weight)
batch_weight.shape

torch.Size([2, 3, 5, 5])

In [10]:
img_gray_naive=img_weights.sum(-3)
batch_gray_naive = batch_weight.sum(-3)

In [11]:
batch_gray_naive.shape

torch.Size([2, 5, 5])

In [12]:
weights_named = torch.tensor([0.2126,0.7152,0.0772],names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0772], names=('channels',))

In [13]:
img_named = img_t.refine_names(...,'channels','rows','columns')
batch_named = batch_t.refine_names(...,'channels','rows','columns')

In [14]:
img_named

tensor([[[-1.1868, -0.2110, -1.2946,  1.0491, -0.8014],
         [ 1.5754,  0.3107, -0.7649,  0.1765,  0.1869],
         [-1.3954,  0.7558, -2.3620, -1.3611, -0.7640],
         [ 1.2083,  0.9279,  0.2932, -1.0009, -0.6761],
         [-2.2376, -0.6900,  1.3789,  1.0597, -0.0886]],

        [[ 2.2504,  0.6935, -1.2463,  0.9669, -1.5942],
         [ 1.0237, -1.7382, -1.4945, -0.3176,  0.8943],
         [-0.7552, -0.0377, -1.2089,  1.1951,  1.3552],
         [ 0.2170,  0.1713, -0.0129,  0.1930,  1.2792],
         [ 1.4446, -1.5114,  0.8920,  0.2609,  0.3935]],

        [[ 0.9918,  0.6454, -1.1049,  0.9195,  1.7985],
         [ 0.7770,  0.2752, -0.4337, -0.4617,  0.1066],
         [-0.6843, -0.0156, -1.0379, -0.9116,  0.6958],
         [-0.2380, -0.6309,  0.0138,  0.2736, -0.7238],
         [ 0.6087,  0.8988,  0.8158, -0.3998, -0.9962]]],
       names=('channels', 'rows', 'columns'))

In [15]:
batch_named

tensor([[[[-1.2248,  0.8224,  0.6409,  0.4427,  0.8285],
          [-0.2669, -2.3206, -0.7529, -0.9412, -1.1082],
          [ 1.3834, -0.7048,  0.7889,  1.0401,  0.8188],
          [-0.2065, -1.2813,  0.4173,  0.0271,  0.0230],
          [ 0.0814,  0.8336,  1.2084,  0.8525, -0.3822]],

         [[-1.3112, -0.2034,  1.3620,  0.2977, -1.6385],
          [-0.5816, -0.9671, -0.3820,  1.1767,  0.1871],
          [ 0.7911, -0.6904,  0.3583, -0.1199, -0.9026],
          [ 0.7997, -0.6620, -0.3076, -1.2689, -0.3593],
          [ 0.6963,  1.2549,  0.8879,  1.1922,  0.1766]],

         [[-0.6096, -0.9504, -2.3129,  0.3664,  0.8728],
          [-0.7889,  0.3114,  0.5534,  0.3326, -0.2005],
          [ 0.3673,  0.3758,  0.6248, -0.5756,  0.6163],
          [ 0.1624, -0.9273,  0.4795, -0.3754, -1.0836],
          [ 0.0809,  0.5413, -1.2631,  0.8946, -1.6769]]],


        [[[-1.9255, -2.2112,  1.3936,  0.1995,  0.7272],
          [ 0.0946, -1.6523,  1.2014, -0.2640,  0.5113],
          [ 0.6448, -1.

In [25]:
weights_named.names,batch_named.names

(('channels',), (None, 'channels', 'rows', 'columns'))

In [26]:
#张量对齐
weight_alighted = weights_named.align_as(img_named)
weight_alighted,weights_named.names,weight_alighted.shape

(tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0772]]], names=('channels', 'rows', 'columns')),
 ('channels',),
 torch.Size([3, 1, 1]))

In [28]:
gray_named = (img_named*weight_alighted).sum('channels')
gray_named,gray_named.shape,gray_named.names,img_named

(tensor([[ 1.4338,  0.5010, -1.2519,  0.9855, -1.1717],
         [ 1.1270, -1.1558, -1.2650, -0.2253,  0.6876],
         [-0.8896,  0.1325, -1.4469,  0.4950,  0.8605],
         [ 0.3937,  0.2711,  0.0542, -0.0537,  0.7153],
         [ 0.6045, -1.1583,  0.9941,  0.3810,  0.1857]],
        names=('rows', 'columns')),
 torch.Size([5, 5]),
 ('rows', 'columns'),
 tensor([[[-1.1868, -0.2110, -1.2946,  1.0491, -0.8014],
          [ 1.5754,  0.3107, -0.7649,  0.1765,  0.1869],
          [-1.3954,  0.7558, -2.3620, -1.3611, -0.7640],
          [ 1.2083,  0.9279,  0.2932, -1.0009, -0.6761],
          [-2.2376, -0.6900,  1.3789,  1.0597, -0.0886]],
 
         [[ 2.2504,  0.6935, -1.2463,  0.9669, -1.5942],
          [ 1.0237, -1.7382, -1.4945, -0.3176,  0.8943],
          [-0.7552, -0.0377, -1.2089,  1.1951,  1.3552],
          [ 0.2170,  0.1713, -0.0129,  0.1930,  1.2792],
          [ 1.4446, -1.5114,  0.8920,  0.2609,  0.3935]],
 
         [[ 0.9918,  0.6454, -1.1049,  0.9195,  1.7985],
       