In [1]:
%matplotlib inline

In [2]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2)

In [11]:
t_c = torch.tensor([0.5,14.0,15.0,28.0,11.0,8.0,
                    3.0,-4.0,6.0,13.0,21.0])
t_u = torch.tensor([35.7,55.9,58.2,81.9,56.3,48.9,
                    33.9,21.8,48.4,60.4,68.4])
t_un = 0.1 * t_u

In [3]:
def model(t_u,w,b):
    return w*t_u +b

In [4]:
def loss_fn(t_p,t_c):
    square_diffs = (t_p - t_c)**2
    return square_diffs.mean()

In [6]:
params = torch.tensor([1.0,0.0],requires_grad=True) #requires_grad=True 证明需要对params 对象进行梯度计算 计算后可以直接调用.grad

In [8]:
params.grad is None

True

In [15]:
loss = loss_fn(model(t_u,*params),t_c) # *params，是将该列表展开，得到列表的每一项
loss

tensor(1763.8848, grad_fn=<MeanBackward0>)

In [16]:
loss.backward()

In [17]:
params.grad #在 w方向的梯度，和在b方向的梯度

tensor([4517.2969,   82.6000])

In [18]:
if params.grad is not None: #这一步的作用是梯度清零
    params.grad.zero_()
params.grad

tensor([0., 0.])

In [21]:
def training_loop(n_epochs,learning_rate,params, t_u,t_c):
    for epoch in range(1,n_epochs+1):
        if params.grad is not None:
            params.grad.zero_()

        t_p = model(t_u,*params)
        loss = loss_fn(t_p,t_c)
        loss.backward()

        with torch.no_grad():
            params -= learning_rate * params.grad

        if epoch % 500 ==0:
            print('Epoch %d, loss %f'%(epoch,float(loss)))

    return params

In [23]:
training_loop(n_epochs=5000,
              learning_rate=1e-2,
              params = torch.tensor([1.0,0.0],requires_grad=True),
              t_u=t_un,
              t_c= t_c)

Epoch 500, loss 7.860115
Epoch 1000, loss 3.828538
Epoch 1500, loss 3.092191
Epoch 2000, loss 2.957698
Epoch 2500, loss 2.933134
Epoch 3000, loss 2.928648
Epoch 3500, loss 2.927830
Epoch 4000, loss 2.927679
Epoch 4500, loss 2.927652
Epoch 5000, loss 2.927647


tensor([  5.3671, -17.3012], requires_grad=True)