In [1]:
%matplotlib inline
import numpy as np
import torch
torch.set_printoptions(edgeitems=2,linewidth=75)

In [2]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0,
                    8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9,
                    33.9, 21.8, 48.4, 60.4, 68.4])
t_un = 0.1 * t_u

In [3]:
def model(t_u,w2,w1,b):
    return w2*t_u**2 + w1*t_u +b

def loss_fn(t_p,t_c):
    squraed_diff = (t_p-t_c)**2
    return squraed_diff.mean()

In [4]:
import torch.optim as optim

In [5]:
params = torch.tensor([1.0,1.0,0.0],requires_grad=True)


In [6]:
n_samples =t_u.shape[0]
n_val = int(0.2*n_samples)
shuffled_index = torch.randperm(n_samples)

train_indices = shuffled_index[:-n_val]
val_indices = shuffled_index[-n_val:]

train_indices,val_indices

(tensor([ 4,  7,  8, 10,  0,  3,  1,  5,  6]), tensor([9, 2]))

In [7]:
train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]

val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]

train_t_un = 0.1* train_t_u
val_t_un = 0.1 * val_t_u


In [22]:
def training_loop(n_epochs,optimizer,params,train_t_u,val_t_u,train_t_c,
                  val_t_c):
    for epoch in range(1,n_epochs+1):
        train_t_p = model(train_t_u,*params)
        train_loss = loss_fn(train_t_p,train_t_c)

        val_t_p = model(val_t_u,*params)
        val_loss = loss_fn(val_t_p,val_t_c)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch <= 3 or epoch % 500 ==0:
            print(f"epoch{epoch}, Training loss {train_loss.item():.4f},"
                  f"Validation loss {val_loss.item():.4f}")

    return params


In [30]:
params =torch.tensor([1.0,1.0,0.0],requires_grad=True)
learning_rate = 1e-2
optimizer = optim.Adam([params],lr=learning_rate)

In [32]:
training_loop(n_epochs=10000,
              optimizer=optimizer,
              params=params,
              train_t_c=train_t_c,
              train_t_u=train_t_un,
              val_t_c=val_t_c,
              val_t_u=val_t_un)

epoch1, Training loss 2.1422,Validation loss 2.8605
epoch2, Training loss 2.1421,Validation loss 2.8604
epoch3, Training loss 2.1419,Validation loss 2.8602
epoch500, Training loss 2.0675,Validation loss 2.8059
epoch1000, Training loss 2.0135,Validation loss 2.7640
epoch1500, Training loss 1.9805,Validation loss 2.7353
epoch2000, Training loss 1.9640,Validation loss 2.7182
epoch2500, Training loss 1.9577,Validation loss 2.7093
epoch3000, Training loss 1.9559,Validation loss 2.7052
epoch3500, Training loss 1.9556,Validation loss 2.7035
epoch4000, Training loss 1.9556,Validation loss 2.7030
epoch4500, Training loss 1.9556,Validation loss 2.7029
epoch5000, Training loss 1.9556,Validation loss 2.7028
epoch5500, Training loss 1.9556,Validation loss 2.7028
epoch6000, Training loss 1.9556,Validation loss 2.7030
epoch6500, Training loss 1.9556,Validation loss 2.7029
epoch7000, Training loss 1.9556,Validation loss 2.7028
epoch7500, Training loss 1.9556,Validation loss 2.7029
epoch8000, Training 

tensor([  0.2887,   2.4304, -10.5816], requires_grad=True)

In [33]:
params

tensor([  0.2887,   2.4304, -10.5816], requires_grad=True)